/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FAQsRouteImport } from './routes/FAQs'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as authenticatedReportsFileIdIndexRouteImport } from './routes/(authenticated)/reports/$fileId/index'

const FAQsRoute = FAQsRouteImport.update({
  id: '/FAQs',
  path: '/FAQs',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedReportsFileIdIndexRoute =
  authenticatedReportsFileIdIndexRouteImport.update({
    id: '/reports/$fileId/',
    path: '/reports/$fileId/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/FAQs': typeof FAQsRoute
  '/': typeof authenticatedIndexRoute
  '/reports/$fileId': typeof authenticatedReportsFileIdIndexRoute
}
export interface FileRoutesByTo {
  '/FAQs': typeof FAQsRoute
  '/': typeof authenticatedIndexRoute
  '/reports/$fileId': typeof authenticatedReportsFileIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/FAQs': typeof FAQsRoute
  '/(authenticated)/': typeof authenticatedIndexRoute
  '/(authenticated)/reports/$fileId/': typeof authenticatedReportsFileIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/FAQs' | '/' | '/reports/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to: '/FAQs' | '/' | '/reports/$fileId'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/FAQs'
    | '/(authenticated)/'
    | '/(authenticated)/reports/$fileId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  FAQsRoute: typeof FAQsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/FAQs': {
      id: '/FAQs'
      path: '/FAQs'
      fullPath: '/FAQs'
      preLoaderRoute: typeof FAQsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/reports/$fileId/': {
      id: '/(authenticated)/reports/$fileId/'
      path: '/reports/$fileId'
      fullPath: '/reports/$fileId'
      preLoaderRoute: typeof authenticatedReportsFileIdIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedIndexRoute: typeof authenticatedIndexRoute
  authenticatedReportsFileIdIndexRoute: typeof authenticatedReportsFileIdIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedIndexRoute: authenticatedIndexRoute,
  authenticatedReportsFileIdIndexRoute: authenticatedReportsFileIdIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  FAQsRoute: FAQsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
