parameters:
  - name: stageName
    type: string
  - name: displayName
    type: string
  - name: dependsOn
    type: object
    default: []
  - name: condition
    type: string
    default: succeeded()

  - name: variableGroup
    type: string
  - name: environmentName
    type: string
  - name: azureSubscription
    type: string

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.displayName }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    variables:
      # Create this variable group in Azure DevOps with environment-specific values:
      # - RESOURCE_GROUP, LOCATION, APP_NAME, ENVIRONMENT, DEPLOYMENT_NAME
      # - SQL_ADMIN_LOGIN, SQL_ADMIN_PASSWORD (secret)
      # - (optional) CORS_ALLOWED_ORIGINS, DEPLOY_EVENTGRID_SUBSCRIPTION, EVENTGRID_* tuning vars
      - group: ${{ parameters.variableGroup }}
    jobs:
      - deployment: deploy
        displayName: Deploy to ${{ parameters.environmentName }}
        environment: ${{ parameters.environmentName }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: Checkout repo

                - download: current
                  artifact: packages

                - task: AzureCLI@2
                  displayName: (optional) Deploy infra (Bicep)
                  condition: and(succeeded(), eq(variables['deployInfra'], 'true'))
                  inputs:
                    azureSubscription: ${{ parameters.azureSubscription }}
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -euo pipefail
                      cd "$(Build.SourcesDirectory)"
                      env \
                        RESOURCE_GROUP="$(RESOURCE_GROUP)" \
                        LOCATION="$(LOCATION)" \
                        APP_NAME="$(APP_NAME)" \
                        ENVIRONMENT="$(ENVIRONMENT)" \
                        DEPLOYMENT_NAME="$(DEPLOYMENT_NAME)" \
                        SQL_ADMIN_LOGIN="$(SQL_ADMIN_LOGIN)" \
                        SQL_ADMIN_PASSWORD="$(SQL_ADMIN_PASSWORD)" \
                        bash infrastructure/azure/scripts/deploy.sh

                - task: AzureCLI@2
                  name: resolveNames
                  displayName: Resolve app names from infra outputs
                  inputs:
                    azureSubscription: ${{ parameters.azureSubscription }}
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -euo pipefail

                      webAppName=$(az deployment group show \
                        --resource-group "$(RESOURCE_GROUP)" \
                        --name "$(DEPLOYMENT_NAME)" \
                        --query "properties.outputs.webAppName.value" -o tsv)

                      functionAppName=$(az deployment group show \
                        --resource-group "$(RESOURCE_GROUP)" \
                        --name "$(DEPLOYMENT_NAME)" \
                        --query "properties.outputs.functionAppName.value" -o tsv)

                      echo "Resolved web app: $webAppName"
                      echo "Resolved function app: $functionAppName"

                      echo "##vso[task.setvariable variable=webAppName]$webAppName"
                      echo "##vso[task.setvariable variable=functionAppName]$functionAppName"

                - task: AzureAppServiceSettings@1
                  displayName: Set Web App runtime settings
                  inputs:
                    azureSubscription: ${{ parameters.azureSubscription }}
                    appName: $(webAppName)
                    resourceGroupName: $(RESOURCE_GROUP)
                    appSettings: |
                      [
                        { "name": "OPENAI_API_KEY", "value": "$(OPENAI_API_KEY)", "slotSetting": false },
                        { "name": "OTEL_EXPORTER_OTLP_ENDPOINT", "value": "$(OTEL_EXPORTER_OTLP_ENDPOINT)", "slotSetting": false },
                        { "name": "OTEL_EXPORTER_OTLP_HEADERS", "value": "$(OTEL_EXPORTER_OTLP_HEADERS)", "slotSetting": false },
                        { "name": "OTEL_EXPORTER_OTLP_PROTOCOL", "value": "grpc", "slotSetting": false },
                        { "name": "OTEL_SERVICE_NAME", "value": "readable.web", "slotSetting": false },
                        { "name": "OTEL_RESOURCE_ATTRIBUTES", "value": "service.name=readable.web,service.environment=$(ENVIRONMENT),deployment.environment.name=$(ENVIRONMENT)", "slotSetting": false },
                        { "name": "PDF_SERVICES_CLIENT_ID", "value": "$(PDF_SERVICES_CLIENT_ID)", "slotSetting": false },
                        { "name": "PDF_SERVICES_CLIENT_SECRET", "value": "$(PDF_SERVICES_CLIENT_SECRET)", "slotSetting": false }
                      ]

                - task: AzureAppServiceSettings@1
                  displayName: Set Function App runtime settings
                  inputs:
                    azureSubscription: ${{ parameters.azureSubscription }}
                    appName: $(functionAppName)
                    resourceGroupName: $(RESOURCE_GROUP)
                    appSettings: |
                      [
                        { "name": "OPENAI_API_KEY", "value": "$(OPENAI_API_KEY)", "slotSetting": false },
                        { "name": "OTEL_EXPORTER_OTLP_ENDPOINT", "value": "$(OTEL_EXPORTER_OTLP_ENDPOINT)", "slotSetting": false },
                        { "name": "OTEL_EXPORTER_OTLP_HEADERS", "value": "$(OTEL_EXPORTER_OTLP_HEADERS)", "slotSetting": false },
                        { "name": "OTEL_EXPORTER_OTLP_PROTOCOL", "value": "grpc", "slotSetting": false },
                        { "name": "OTEL_SERVICE_NAME", "value": "readable.worker", "slotSetting": false },
                        { "name": "OTEL_RESOURCE_ATTRIBUTES", "value": "service.name=readable.worker,service.environment=$(ENVIRONMENT),deployment.environment.name=$(ENVIRONMENT)", "slotSetting": false },
                        { "name": "PDF_SERVICES_CLIENT_ID", "value": "$(PDF_SERVICES_CLIENT_ID)", "slotSetting": false },
                        { "name": "PDF_SERVICES_CLIENT_SECRET", "value": "$(PDF_SERVICES_CLIENT_SECRET)", "slotSetting": false }
                      ]

                - task: AzureWebApp@1
                  displayName: Deploy web app
                  inputs:
                    azureSubscription: ${{ parameters.azureSubscription }}
                    appType: webAppLinux
                    appName: $(webAppName)
                    package: $(Pipeline.Workspace)/packages/webapp.zip

                - task: AzureFunctionApp@2
                  displayName: Deploy function app
                  inputs:
                    azureSubscription: ${{ parameters.azureSubscription }}
                    appType: functionAppLinux
                    appName: $(functionAppName)
                    package: $(Pipeline.Workspace)/packages/functionapp.zip
                    isFlexConsumption: true

