#!/usr/bin/env bash
set -euo pipefail

SUBSCRIPTION_NAME="UC Davis CAES Production"
SUBSCRIPTION_ID="003283b1-cc5e-417a-b037-01ff3c05537b"

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
DEPLOY_SCRIPT="$SCRIPT_DIR/deploy.sh"

RESOURCE_GROUP="rg-readable-prod"
APP_NAME="readable"
ENVIRONMENT="prod"
DEPLOYMENT_NAME="${DEPLOYMENT_NAME:-${APP_NAME}-${ENVIRONMENT}}"
CORS_ALLOWED_ORIGINS='["*"]'
SQL_ADMIN_LOGIN="readable"
LOCATION="westus2"

env \
  SUBSCRIPTION_NAME="$SUBSCRIPTION_NAME" \
  SUBSCRIPTION_ID="$SUBSCRIPTION_ID" \
  RESOURCE_GROUP="$RESOURCE_GROUP" \
  LOCATION="$LOCATION" \
  APP_NAME="$APP_NAME" \
  ENVIRONMENT="$ENVIRONMENT" \
  DEPLOYMENT_NAME="$DEPLOYMENT_NAME" \
  CORS_ALLOWED_ORIGINS="$CORS_ALLOWED_ORIGINS" \
  SQL_ADMIN_LOGIN="$SQL_ADMIN_LOGIN" \
  SQL_ADMIN_PASSWORD="${SQL_ADMIN_PASSWORD:-}" \
  "$DEPLOY_SCRIPT"
