#!/usr/bin/env bash
set -euo pipefail

SUBSCRIPTION_NAME="UC Davis CAES Test"
SUBSCRIPTION_ID="105dede4-4731-492e-8c28-5121226319b0"

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
DEPLOY_SCRIPT="$SCRIPT_DIR/deploy.sh"

RESOURCE_GROUP="rg-readable-dev"
APP_NAME="readable"
ENVIRONMENT="dev"
CORS_ALLOWED_ORIGINS='["*"]'
SQL_ADMIN_LOGIN="readable"
LOCATION="westus2"

env \
  SUBSCRIPTION_NAME="$SUBSCRIPTION_NAME" \
  SUBSCRIPTION_ID="$SUBSCRIPTION_ID" \
  RESOURCE_GROUP="$RESOURCE_GROUP" \
  LOCATION="$LOCATION" \
  APP_NAME="$APP_NAME" \
  ENVIRONMENT="$ENVIRONMENT" \
  CORS_ALLOWED_ORIGINS="$CORS_ALLOWED_ORIGINS" \
  SQL_ADMIN_LOGIN="$SQL_ADMIN_LOGIN" \
  SQL_ADMIN_PASSWORD="${SQL_ADMIN_PASSWORD:-}" \
  "$DEPLOY_SCRIPT"
